# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from pathlib import Path

datas = [
    ('app_icon.png', '.'),
    ('app.ico', '.'),
    ('assets', 'assets'),
    ('sample_words.txt', '.'),
]
binaries = []
hiddenimports = [
    'PyQt6',
    'PyQt6.QtCore',
    'PyQt6.QtGui',
    'PyQt6.QtWidgets',
    'win32com.client',
    'pythoncom',
    'core',
    'core.database',
    'core.gamification',
    'core.retention_analytics',
    'core.phonetics',
    'core.word_packs',
    'core.daily_quests',
    'services',
    'services.tts_service',
    'services.speech_service',
    'services.sound_effects',
    'services.cefr_service',
    'services.topic_service',
    'services.clipboard_service',
    'services.global_dict_service',
    'services.game_word_provider',
    'services.daily_quests_service',
    'utils',
    'utils.logger',
    'utils.importer',
    'utils.reader_data',
    'utils.single_instance',
    'utils.text_search_utils',
    'ui',
    'ui.theme_manager',
    'ui.main_window',
    'ui.views',
    'ui.views.dashboard_view',
    'ui.views.dictionary_view',
    'ui.views.practice_view',
    'ui.views.audio_player_view',
    'ui.views.reader_view',
    'ui.views.topic_words_view',
    'ui.views.settings_view',
    'ui.games',
    'ui.games.blitz_game',
    'ui.games.match_game',
    'ui.games.word_fall_game',
    'ui.games.crossword_game',
    'ui.dialogs',
    'ui.dialogs.word_packs_dialog',
    'ui.dialogs.quick_capture_dialog',
    'ui.dialogs.spotlight_search_dialog',
    'ui.dialogs.achievements_dialog',
    'ui.dialogs.worksheet_dialog',
    'ui.dialogs.import_dialog',
    'ui.components',
    'ui.components.mini_widget',
    'ui.components.daily_quests_widget',
    'ui.components.game_source_selector',
    'logger',
    'database',
    'tts',
    'theme_manager',
    'gamification',
    'phonetics',
    'retention_analytics',
    'sound_effects',
    'speech_recognizer',
    'topic_service',
    'word_packs',
    'daily_quests_service',
    'global_dict_service',
    'cefr_service',
    'clipboard_monitor',
    'reader_data',
    'importer',
    'text_search_utils',
]

excludes = [
    'matplotlib',
    'scipy',
    'pandas',
    'tkinter',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='VocabMaster',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app.ico'],
)
