"""
Vocab Master Pro — Tayyor So'z Paketlari (Pre-made Word Packs).
O'quvchilar, talabalar va dasturchilar uchun saralangan maxsus lug'at to'plamlari.
Har bir so'z inglizcha, o'zbekcha tarjimasi va amaliy misol gapi (example) bilan ta'minlangan.
"""

WORD_PACKS = [
    {
        "id": "essential",
        "title": "🌟 Oltin 100 ta so'z (Essential Vocabulary)",
        "icon": "🌟",
        "level": "A2 - B1",
        "badge_color": "#F59E0B",
        "description": "Ingliz tilidagi eng ko'p ishlatiladigan, kundalik muloqot va asosiy tushunchalar uchun poydevor bo'luvchi 100 ta zaruriy so'z.",
        "words": [
            {"english": "achieve", "uzbek": "erishmoq, qo'lga kiritmoq", "example": "She worked hard to achieve her dream."},
            {"english": "advantage", "uzbek": "afzallik, ustunlik", "example": "Speed is the main advantage of this system."},
            {"english": "approach", "uzbek": "yondashuv, yaqinlashmoq", "example": "We need a new approach to solve this problem."},
            {"english": "attitude", "uzbek": "munosabat, qarash", "example": "A positive attitude helps you overcome difficulties."},
            {"english": "behavior", "uzbek": "xulq-atvor, yurish-turish", "example": "His behavior changed completely after the meeting."},
            {"english": "benefit", "uzbek": "foyda, naf", "example": "Regular exercise brings great benefits to health."},
            {"english": "challenge", "uzbek": "qiyinchilik, chaqiruv", "example": "Learning a new language is always an exciting challenge."},
            {"english": "community", "uzbek": "jamoa, jamiyat", "example": "The local community organized a charity event."},
            {"english": "compare", "uzbek": "taqqoslamoq, solishtirmoq", "example": "You should not compare your progress with others."},
            {"english": "conclude", "uzbek": "xulosa qilmoq, yakunlamoq", "example": "The report concludes that sales have increased."},
            {"english": "consider", "uzbek": "hisobga olmoq, o'ylab ko'rmoq", "example": "Please consider all options before making a decision."},
            {"english": "create", "uzbek": "yaratmoq, vujudga keltirmoq", "example": "Artists create beauty out of ordinary things."},
            {"english": "culture", "uzbek": "madaniyat", "example": "Travel helps you understand different cultures."},
            {"english": "decide", "uzbek": "qaror qilmoq", "example": "I need more time to decide what to do."},
            {"english": "describe", "uzbek": "tasvirlamoq, ta'riflamoq", "example": "Can you describe the person you saw?"},
            {"english": "develop", "uzbek": "rivojlantirmoq, taraqqiy etmoq", "example": "We need to develop our communication skills."},
            {"english": "difference", "uzbek": "farq, tafovut", "example": "Can you tell the difference between these two words?"},
            {"english": "discover", "uzbek": "kashf qilmoq, topmoq", "example": "Scientists continue to discover new species."},
            {"english": "economy", "uzbek": "iqtisodiyot", "example": "Tourism plays a big role in the national economy."},
            {"english": "effective", "uzbek": "samarali, ta'sirli", "example": "This is an effective strategy for learning words."},
            {"english": "environment", "uzbek": "atrof-muhit", "example": "We must protect our environment for future generations."},
            {"english": "essential", "uzbek": "muhim, zaruriy", "example": "Water is essential for all living creatures."},
            {"english": "evidence", "uzbek": "dalil, isbot", "example": "There is strong evidence supporting this theory."},
            {"english": "experience", "uzbek": "tajriba, kechinma", "example": "She gained valuable experience working abroad."},
            {"english": "explain", "uzbek": "tushuntirmoq, izohlamoq", "example": "The teacher explained the grammar rule clearly."},
            {"english": "explore", "uzbek": "o'rganmoq, tadqiq qilmoq", "example": "Let us explore new possibilities together."},
            {"english": "factor", "uzbek": "omil", "example": "Time is an important factor in this project."},
            {"english": "focus", "uzbek": "diqqatni qaratmoq", "example": "Try to focus on one task at a time."},
            {"english": "generate", "uzbek": "ishlab chiqarmoq, yaratmoq", "example": "Solar panels generate clean electricity."},
            {"english": "goal", "uzbek": "maqsad", "example": "Set a clear goal and work toward it every day."},
            {"english": "growth", "uzbek": "o'sish, rivojlanish", "example": "The company experienced rapid growth last year."},
            {"english": "identify", "uzbek": "aniqlamoq, tanimoq", "example": "The doctor was able to identify the disease quickly."},
            {"english": "impact", "uzbek": "ta'sir", "example": "Technology has a massive impact on modern education."},
            {"english": "improve", "uzbek": "yaxshilamoq, rivojlantirmoq", "example": "Daily practice will improve your English fluency."},
            {"english": "include", "uzbek": "o'z ichiga olmoq", "example": "The price includes breakfast and airport transfer."},
            {"english": "increase", "uzbek": "oshirmoq, ko'paytirmoq", "example": "We want to increase our daily study time."},
            {"english": "indicate", "uzbek": "ko'rsatmoq, dalolat bermoq", "example": "The symptoms indicate a common cold."},
            {"english": "influence", "uzbek": "ta'sir o'tkazmoq", "example": "Parents greatly influence their children's habits."},
            {"english": "information", "uzbek": "ma'lumot", "example": "You can find useful information on their website."},
            {"english": "insight", "uzbek": "teran tushunish, idrok", "example": "His book provides deep insights into human psychology."},
            {"english": "inspire", "uzbek": "ilhomlantirmoq", "example": "Great leaders inspire people to do their best."},
            {"english": "integrate", "uzbek": "birlashtirmoq, integratsiya qilmoq", "example": "The software is easy to integrate into existing workflows."},
            {"english": "introduce", "uzbek": "tanishtirmoq, joriy qilmoq", "example": "Let me introduce you to our new colleague."},
            {"english": "issue", "uzbek": "muammo, masala", "example": "We discussed environmental issues at the conference."},
            {"english": "knowledge", "uzbek": "bilim", "example": "Knowledge is power when put into practice."},
            {"english": "leadership", "uzbek": "yetakchilik, rahbarlik", "example": "Strong leadership helped the team succeed."},
            {"english": "maintain", "uzbek": "saqlab turmoq", "example": "It is important to maintain high quality standards."},
            {"english": "manage", "uzbek": "boshqarmoq, uddalamoq", "example": "She knows how to manage her time effectively."},
            {"english": "measure", "uzbek": "o'lchamoq, chora", "example": "We need to measure the results accurately."},
            {"english": "method", "uzbek": "usul, metod", "example": "This method has proven very successful."},
            {"english": "necessary", "uzbek": "zarur, kerakli", "example": "Patience is necessary when mastering a new skill."},
            {"english": "obtain", "uzbek": "qo'lga kiritmoq, olmoq", "example": "You must obtain a permit before entering."},
            {"english": "opportunity", "uzbek": "imkoniyat", "example": "Do not miss this great opportunity to study abroad."},
            {"english": "participate", "uzbek": "ishtirok etmoq", "example": "Many students participate in extracurricular activities."},
            {"english": "performance", "uzbek": "samaradorlik, ijro", "example": "His performance improved significantly this semester."},
            {"english": "perspective", "uzbek": "nuqtai nazar, dunyoqarash", "example": "Looking at things from another perspective is helpful."},
            {"english": "practice", "uzbek": "mashq qilmoq, amaliyot", "example": "Practice makes perfect."},
            {"english": "prepare", "uzbek": "tayyorlanmoq", "example": "We must prepare thoroughly for the upcoming exam."},
            {"english": "prevent", "uzbek": "oldini olmoq", "example": "Good habits prevent many health problems."},
            {"english": "primary", "uzbek": "asosiy, birlamchi", "example": "Education is our primary focus."},
            {"english": "priority", "uzbek": "ustuvor vazifa", "example": "Safety is always our top priority."},
            {"english": "problem", "uzbek": "muammo", "example": "Every problem has a solution if you think creatively."},
            {"english": "process", "uzbek": "jarayon", "example": "Learning a language is a gradual process."},
            {"english": "produce", "uzbek": "ishlab chiqarmoq", "example": "The factory produces high quality textiles."},
            {"english": "progress", "uzbek": "o'sish, ilgarilash", "example": "You are making steady progress in your English."},
            {"english": "promote", "uzbek": "rag'batlantirmoq, lavozimini oshirmoq", "example": "We want to promote healthy living among youth."},
            {"english": "protect", "uzbek": "himoya qilmoq", "example": "Wear a helmet to protect your head."},
            {"english": "provide", "uzbek": "ta'minlamoq, bermoq", "example": "The course provides all necessary learning materials."},
            {"english": "quality", "uzbek": "sifat", "example": "Focus on quality rather than quantity."},
            {"english": "realize", "uzbek": "anglab yetmoq", "example": "I did not realize how late it was."},
            {"english": "recognize", "uzbek": "tanimoq, e'tirof etmoq", "example": "I did not recognize him after so many years."},
            {"english": "reduce", "uzbek": "kamaytirmoq", "example": "We should reduce paper waste in the office."},
            {"english": "reflect", "uzbek": "aks ettirmoq, mulohaza qilmoq", "example": "Take time to reflect on what you learned today."},
            {"english": "relationship", "uzbek": "munosabat, aloqa", "example": "Trust is the foundation of any good relationship."},
            {"english": "relevant", "uzbek": "aloqador, ahamiyatli", "example": "Please provide all relevant documents."},
            {"english": "require", "uzbek": "talab qilmoq", "example": "This job requires excellent communication skills."},
            {"english": "research", "uzbek": "tadqiqot", "example": "Scientific research leads to innovation."},
            {"english": "resource", "uzbek": "resurs, manba", "example": "The library is an excellent resource for students."},
            {"english": "respond", "uzbek": "javob qaytarmoq", "example": "She quickly responded to my email."},
            {"english": "result", "uzbek": "natija", "example": "The test results will be announced tomorrow."},
            {"english": "reveal", "uzbek": "oshkor qilmoq", "example": "The survey revealed surprising facts about reading habits."},
            {"english": "significant", "uzbek": "muhim, sezilarli", "example": "There has been a significant increase in online learning."},
            {"english": "solution", "uzbek": "yechim", "example": "Finding a workable solution requires teamwork."},
            {"english": "source", "uzbek": "manba", "example": "Always cite your sources when writing an essay."},
            {"english": "specific", "uzbek": "aniq, muayyan", "example": "Can you give me a specific example?"},
            {"english": "strategy", "uzbek": "strategiya, reja", "example": "A well-planned strategy ensures victory."},
            {"english": "structure", "uzbek": "tuzilma, bino", "example": "The grammar structure is easy to understand."},
            {"english": "success", "uzbek": "muvaffaqiyat", "example": "Dedication is the secret to lasting success."},
            {"english": "support", "uzbek": "qo'llab-quvvatlamoq", "example": "Thank you for supporting me through hard times."},
            {"english": "technology", "uzbek": "texnologiya", "example": "Modern technology makes distance learning possible."},
            {"english": "tendency", "uzbek": "moyillik, tendensiya", "example": "There is a growing tendency toward remote work."},
            {"english": "theory", "uzbek": "nazariya", "example": "Einstein's theory changed modern physics forever."},
            {"english": "traditional", "uzbek": "an'anaviy", "example": "They wore beautiful traditional clothes at the festival."},
            {"english": "understand", "uzbek": "tushunmoq", "example": "I understand your point completely."},
            {"english": "unique", "uzbek": "noyob, betakror", "example": "Each person has a unique learning style."},
            {"english": "value", "uzbek": "qadr-qimmat, baholamoq", "example": "We value honesty and dedication in our team."},
            {"english": "variety", "uzbek": "turfa xillik, xilma-xillik", "example": "The market offers a wide variety of fresh fruits."},
            {"english": "various", "uzbek": "turli xil, har xil", "example": "There are various ways to memorize new vocabulary."},
            {"english": "visible", "uzbek": "ko'rinadigan, aniq", "example": "The mountain was visible from miles away."},
        ]
    },
    {
        "id": "ielts",
        "title": "🎓 IELTS Band 7+ Academic Vocabulary",
        "icon": "🎓",
        "level": "B2 - C1",
        "badge_color": "#8B5CF6",
        "description": "IELTS Writing va Reading imtihonlarida yuqori ball (Band 7+) olish uchun eng qimmatli akademik so'zlar to'plami.",
        "words": [
            {"english": "acquire", "uzbek": "o'zlashtirmoq, orttirmoq", "example": "Children acquire language naturally through immersion."},
            {"english": "advocate", "uzbek": "tarafdor bo'lmoq, yoqlamoq", "example": "Many experts advocate for renewable energy sources."},
            {"english": "allocate", "uzbek": "taqsimlamoq, ajratmoq", "example": "The government allocated extra funds for healthcare."},
            {"english": "ambiguous", "uzbek": "noaniq, ikki ma'noli", "example": "The instructions were ambiguous, causing confusion."},
            {"english": "anticipate", "uzbek": "oldindan sezmoq, kutmoq", "example": "We anticipate a sharp rise in demand this winter."},
            {"english": "coherent", "uzbek": "mantiqiy, bog'langan", "example": "Your essay should have a clear and coherent structure."},
            {"english": "commence", "uzbek": "boshlanmoq, boshlamoq", "example": "The lecture will commence promptly at nine o'clock."},
            {"english": "compensate", "uzbek": "qoplamoq, kompensatsiya qilmoq", "example": "The company compensated workers for the extra hours."},
            {"english": "comprehensive", "uzbek": "har tomonlama, to'liq", "example": "The report offers a comprehensive review of the economy."},
            {"english": "consensus", "uzbek": "yakdillik, umumiy kelishuv", "example": "The committee reached a consensus on the proposal."},
            {"english": "constitute", "uzbek": "tashkil qilmoq, hisoblanmoq", "example": "Women constitute over half of university graduates."},
            {"english": "constrain", "uzbek": "cheklamoq, majburlamoq", "example": "Budget limits constrain our ability to expand."},
            {"english": "contradict", "uzbek": "zid kelmoq, inkor qilmoq", "example": "The new findings contradict previous assumptions."},
            {"english": "deduce", "uzbek": "mantiqan xulosa chiqarmoq", "example": "From the clues, the detective deduced what had happened."},
            {"english": "depict", "uzbek": "tasvirlamoq", "example": "The documentary depicts life in rural communities."},
            {"english": "diminish", "uzbek": "kamaymoq, zaiflashmoq", "example": "The pain will gradually diminish after taking medicine."},
            {"english": "discreet", "uzbek": "ehtiyotkor, bosiq", "example": "He made discreet inquiries about the job opening."},
            {"english": "empirical", "uzbek": "tajribaga asoslangan", "example": "Her conclusions are backed by solid empirical data."},
            {"english": "enhance", "uzbek": "kuchaytirmoq, sifatini oshirmoq", "example": "Interactive tools enhance student engagement."},
            {"english": "explicit", "uzbek": "ochiq-oydin, aniq", "example": "The teacher gave explicit directions for the project."},
            {"english": "fluctuate", "uzbek": "o'zgarib turmoq, tebranmoq", "example": "Prices fluctuate depending on supply and demand."},
            {"english": "hierarchy", "uzbek": "iyerarxiya, pog'ona", "example": "There is a strict hierarchy in military organizations."},
            {"english": "hypothesis", "uzbek": "gipoteza, ilmiy faraz", "example": "Scientists conducted experiments to test the hypothesis."},
            {"english": "inevitable", "uzbek": "muqarrar, qochib bo'lmas", "example": "Change is an inevitable part of modern life."},
            {"english": "inherent", "uzbek": "tug'ma, ajralmas", "example": "Every sport has an inherent risk of minor injuries."},
            {"english": "mitigate", "uzbek": "yumshatmoq, xavfni kamaytirmoq", "example": "Planting trees helps mitigate the effects of pollution."},
            {"english": "notion", "uzbek": "tushuncha, fikr", "example": "He dismissed the notion that success is purely luck."},
            {"english": "perceive", "uzbek": "idrok etmoq, his qilmoq", "example": "People perceive color differently in various lights."},
            {"english": "plausible", "uzbek": "haqiqatga yaqin, ishonarli", "example": "She offered a plausible explanation for her absence."},
            {"english": "prevalent", "uzbek": "keng tarqalgan", "example": "Stress is prevalent among high school seniors."},
            {"english": "qualitative", "uzbek": "sifatga oid", "example": "The researchers conducted qualitative interviews."},
            {"english": "quantitative", "uzbek": "miqdoriy", "example": "Quantitative analysis showed a 20 percent increase."},
            {"english": "scrutinize", "uzbek": "sinchiklab tekshirmoq", "example": "Auditors will scrutinize every financial transaction."},
            {"english": "subsequent", "uzbek": "keyingi, undan keyin keladigan", "example": "Subsequent studies confirmed the original findings."},
            {"english": "substantial", "uzbek": "sezilarli, salmoqli", "example": "A substantial amount of money was saved."},
            {"english": "subtle", "uzbek": "nozik, sezilmas", "example": "There was a subtle change in his tone of voice."},
            {"english": "trigger", "uzbek": "sabab bo'lmoq, qo'zg'atmoq", "example": "Cold weather can trigger asthma attacks."},
            {"english": "unprecedented", "uzbek": "misli ko'rilmagan", "example": "The crisis caused unprecedented economic disruption."},
            {"english": "viable", "uzbek": "yashovchan, hayotiy", "example": "Solar energy is now a commercially viable option."},
            {"english": "advocate", "uzbek": "himoyachi, yoqlovchi", "example": "She is a passionate advocate of human rights."}
        ]
    },
    {
        "id": "tech",
        "title": "💻 IT & Dasturlash (Tech & Coding)",
        "icon": "💻",
        "level": "Professional Tech",
        "badge_color": "#10B981",
        "description": "Dasturchilar, testerlar va IT mutaxassislari uchun kod yozish, dokumentatsiya va suhbatlarda kerak bo'ladigan texnik terminlar.",
        "words": [
            {"english": "algorithm", "uzbek": "algoritm, amallar ketma-ketligi", "example": "We optimized the search algorithm to reduce complexity."},
            {"english": "architecture", "uzbek": "dasturiy arxitektura", "example": "Microservice architecture allows independent scaling."},
            {"english": "authentication", "uzbek": "autentifikatsiya, shaxsni tasdiqlash", "example": "Two-factor authentication adds extra security."},
            {"english": "authorization", "uzbek": "avtorizatsiya, ruxsat berish", "example": "Authorization ensures users access only their own data."},
            {"english": "backend", "uzbek": "server qismi", "example": "The backend handles business logic and database queries."},
            {"english": "benchmark", "uzbek": "samaradorlik testi", "example": "Running benchmarks showed a 40% memory saving."},
            {"english": "breakpoint", "uzbek": "to'xtash nuqtasi (debugging)", "example": "Set a breakpoint inside the function to inspect variables."},
            {"english": "buffer", "uzbek": "vaqtinchalik xotira maydoni", "example": "Audio streaming uses a buffer to prevent stuttering."},
            {"english": "cache", "uzbek": "kesh, tezkor xotira", "example": "Redis is commonly used as an in-memory cache."},
            {"english": "callback", "uzbek": "qayta chaqiriluvchi funksiya", "example": "Pass a callback function to handle the async response."},
            {"english": "compiler", "uzbek": "kompilyator", "example": "The compiler translates source code into machine bytecode."},
            {"english": "concurrency", "uzbek": "bir vaqtda bajarilish, parallellik", "example": "Go routines make handling concurrency straightforward."},
            {"english": "deadlock", "uzbek": "tupik, o'zaro kutib qolish", "example": "Improper mutex locks can cause a program deadlock."},
            {"english": "debugging", "uzbek": "xatoliklarni topish va tuzatish", "example": "Debugging often takes more time than writing new code."},
            {"english": "dependency", "uzbek": "bog'liqlik (kutubxona)", "example": "Pip installs third-party dependencies from requirements.txt."},
            {"english": "deployment", "uzbek": "joylashtirish, ishga tushirish (deploy)", "example": "Automated deployment saves developers hours of manual work."},
            {"english": "encapsulation", "uzbek": "inkapsulyatsiya (OOP)", "example": "Encapsulation hides the internal state of an object."},
            {"english": "endpoint", "uzbek": "API oxirgi manzili", "example": "The REST endpoint returns user profile data in JSON."},
            {"english": "exception", "uzbek": "istisno holati, kutilmagan xato", "example": "Catch the exception to prevent the application from crashing."},
            {"english": "execute", "uzbek": "ishga tushirmoq, bajarmoq", "example": "The CPU executes millions of instructions per second."},
            {"english": "framework", "uzbek": "freymvork, dasturiy qolip", "example": "Django is a popular Python web framework."},
            {"english": "frontend", "uzbek": "foydalanuvchi interfeysi qismi", "example": "Modern frontends are built using React or Vue."},
            {"english": "immutable", "uzbek": "o'zgarmas (ma'lumot)", "example": "Tuples and strings in Python are immutable."},
            {"english": "inheritance", "uzbek": "meros olish (OOP)", "example": "Class inheritance promotes code reuse across models."},
            {"english": "instance", "uzbek": "nusxa, obyekt nusxasi", "example": "Create a new instance of the DatabaseConnection class."},
            {"english": "iteration", "uzbek": "takrorlanish, qadam", "example": "The loop executes ten iterations before terminating."},
            {"english": "latency", "uzbek": "kechikish vaqti (ping)", "example": "Low latency is critical for online multiplayer gaming."},
            {"english": "middleware", "uzbek": "oraliq dasturiy ta'minot", "example": "Authentication middleware checks tokens before each request."},
            {"english": "migration", "uzbek": "ma'lumotlar bazasi migratsiyasi", "example": "Run the migration script to add the new table column."},
            {"english": "multithreading", "uzbek": "ko'p oqimli ishlash", "example": "Multithreading improves responsiveness in GUI desktop apps."},
            {"english": "namespace", "uzbek": "nomlar fazosi", "example": "Namespaces prevent naming collisions in large projects."},
            {"english": "optimization", "uzbek": "optimallashtirish", "example": "Code optimization reduced loading time from 5s to 1s."},
            {"english": "overflow", "uzbek": "to'lib toshish (xotira)", "example": "Deep recursion without a base case causes stack overflow."},
            {"english": "pagination", "uzbek": "sahifalarga bo'lish", "example": "API pagination returns results 20 items per page."},
            {"english": "parameter", "uzbek": "parametr, argument", "example": "Pass the user ID as a parameter to the function."},
            {"english": "payload", "uzbek": "foydali yuk, so'rov tanasi", "example": "The POST request carries a JSON payload with form data."},
            {"english": "pipeline", "uzbek": "konveyer (CI/CD)", "example": "The CI/CD pipeline runs unit tests on every git push."},
            {"english": "polymorphism", "uzbek": "polimorfizm (OOP)", "example": "Polymorphism allows different classes to share an interface."},
            {"english": "protocol", "uzbek": "tarmoq protokoli", "example": "HTTPS is the standard secure communication protocol."},
            {"english": "query", "uzbek": "ma'lumotlar bazasi so'rovi", "example": "Write an indexed SQL query for faster data retrieval."},
            {"english": "recursion", "uzbek": "rekursiya, o'zini chaqirish", "example": "A recursive function must have a terminating base condition."},
            {"english": "refactoring", "uzbek": "kodni qayta ishlash, tozalash", "example": "Refactoring improves readability without altering functionality."},
            {"english": "repository", "uzbek": "ombor, kod repozitoriysi", "example": "Clone the git repository to your local computer."},
            {"english": "responsive", "uzbek": "moslashuvchan (dizayn)", "example": "Responsive web design adapts seamlessly to mobile screens."},
            {"english": "runtime", "uzbek": "ishlash vaqti muhiti", "example": "Python runtime executes bytecode inside a virtual machine."},
            {"english": "sandbox", "uzbek": "qumloq, izolyatsiyalangan muhit", "example": "Run untrusted scripts inside a sandbox for safety."},
            {"english": "scalability", "uzbek": "kengayuvchanlik", "example": "Cloud computing provides high scalability during traffic spikes."},
            {"english": "serialization", "uzbek": "obyektni matnga aylantirish", "example": "JSON serialization transforms objects into string format."},
            {"english": "syntax", "uzbek": "sintaksis, til qoidalari", "example": "A missing closing bracket causes a syntax error."},
            {"english": "throughput", "uzbek": "o'tkazuvchanlik quvvati", "example": "We benchmarked the server throughput under 10,000 requests."},
            {"english": "transaction", "uzbek": "tranzaksiya (DB)", "example": "Wrap database operations in a transaction for atomicity."},
            {"english": "validation", "uzbek": "tekshirish, tasdiqlash", "example": "Input validation prevents SQL injection attacks."}
        ]
    },
    {
        "id": "idioms",
        "title": "🗣 Kundalik Iboralar & Frazeologizmlar (Collocations)",
        "icon": "🗣",
        "level": "Spoken English",
        "badge_color": "#EC4899",
        "description": "Chet elliklar kabi tabiiy va jonli gapirish uchun eng mashhur 35 ta inglizcha ibora va turg'un birikmalar.",
        "words": [
            {"english": "call it a day", "uzbek": "ishni tugatmoq, bugunga yetar demoq", "example": "We have been working for ten hours, let's call it a day."},
            {"english": "piece of cake", "uzbek": "juda oson ish, bir cho'qishda", "example": "Don't worry about the driving test, it is a piece of cake."},
            {"english": "break the ice", "uzbek": "muzni eritmoq, suhbatni boshlab berish", "example": "He told a funny joke to break the ice at the party."},
            {"english": "bite the bullet", "uzbek": "tishni tishga qo'ymoq, og'ir ishga botinmoq", "example": "I hate dentist visits, but I just have to bite the bullet."},
            {"english": "under the weather", "uzbek": "o'zini noxush/betob his qilmoq", "example": "I cannot come to work today because I feel under the weather."},
            {"english": "once in a blue moon", "uzbek": "juda kamdan-kam, yilda bir marta", "example": "He lives far away, so we only see him once in a blue moon."},
            {"english": "see eye to eye", "uzbek": "fikrlari bir joydan chiqmoq, hamfikr bo'lmoq", "example": "My brother and I rarely see eye to eye on politics."},
            {"english": "costs an arm and a leg", "uzbek": "juda qimmat turadi, o't tushgan", "example": "That luxury sports car costs an arm and a leg."},
            {"english": "burn the midnight oil", "uzbek": "tun bo'yi bedor ishlamoq/o'qimoq", "example": "She burned the midnight oil to prepare for the bar exam."},
            {"english": "cut corners", "uzbek": "ishni osonlatib sifatdan urmoq, chala qilmoq", "example": "Never cut corners when building electrical wiring."},
            {"english": "back to the drawing board", "uzbek": "boshidan boshlamoq (reja o'xshamaganda)", "example": "The prototype failed, so it is back to the drawing board."},
            {"english": "beat around the bush", "uzbek": "gapni aylantirmoq, asosiy mavzudan qochmoq", "example": "Stop beating around the bush and tell me the truth."},
            {"english": "by the way", "uzbek": "darvoqe, aytgandek", "example": "By the way, did you remember to buy the milk?"},
            {"english": "as soon as possible", "uzbek": "iloji boricha tezroq", "example": "Please send the completed report as soon as possible."},
            {"english": "keep in touch", "uzbek": "aloqada bo'lib turmoq", "example": "It was great seeing you; let's keep in touch!"},
            {"english": "make up your mind", "uzbek": "bir qarorga kelmoq", "example": "You need to make up your mind before the deadline."},
            {"english": "on the other hand", "uzbek": "boshqa tomondan qaraganda", "example": "The job pays well; on the other hand, it requires long hours."},
            {"english": "in the long run", "uzbek": "uzoq muddatda, pirovardida", "example": "Investing in your education always pays off in the long run."},
            {"english": "sooner or later", "uzbek": "erta yo kech, baribir", "example": "Sooner or later, hard work brings rewarding results."},
            {"english": "from scratch", "uzbek": "noldan, boshidan", "example": "He built his tech startup completely from scratch."},
            {"english": "out of the blue", "uzbek": "to'satdan, kutilmaganda", "example": "She received a job offer out of the blue from Google."},
            {"english": "point of view", "uzbek": "nuqtai nazar", "example": "Try to look at the situation from a customer's point of view."},
            {"english": "give it a shot", "uzbek": "urinib/sinab ko'rmoq", "example": "Even if it looks hard, you should definitely give it a shot."},
            {"english": "hit the books", "uzbek": "dars qilmoq, kitob o'qishga kirishmoq", "example": "Exams start next Monday, so it's time to hit the books."},
            {"english": "keep an eye on", "uzbek": "ko'z-quloq bo'lmoq", "example": "Could you please keep an eye on my luggage for a minute?"},
            {"english": "let someone down", "uzbek": "umidini puchga chiqarmoq, pand bermoq", "example": "I promised to help, and I will not let you down."},
            {"english": "make ends meet", "uzbek": "ro'zg'orni zo'rg'a tebratmoq", "example": "Many families worked two jobs to make ends meet."},
            {"english": "on the same page", "uzbek": "bir xil tushunmoq, hamfikr bo'lmoq", "example": "Let us have a quick sync to make sure we are on the same page."},
            {"english": "ring a bell", "uzbek": "tanish tuyulmoq, eshitgandek bo'lmoq", "example": "His name rings a bell, but I cannot recall his face."},
            {"english": "take it easy", "uzbek": "o'zingni bosing, xotirjam bo'ling", "example": "Take it easy; the weekend is finally here."},
            {"english": "time flies", "uzbek": "vaqt qushdek uchadi", "example": "Time flies when you are having fun with friends."},
            {"english": "up in the air", "uzbek": "hali noaniq, havoda muallaq", "example": "Our vacation plans are still up in the air due to work."},
            {"english": "spill the beans", "uzbek": "sirni ochib qo'ymoq", "example": "Don't spill the beans about the surprise birthday party."},
            {"english": "step up your game", "uzbek": "o'yinni/harakatni kuchaytirmoq", "example": "Competition is fierce, so you must step up your game."},
            {"english": "hit the nail on the head", "uzbek": "gapning nishoniga urmoq, to'g'ri topmoq", "example": "Your analysis hit the nail on the head perfectly."}
        ]
    }
]


def get_all_packs() -> list[dict]:
    """Barcha mavjud paketlar ro'yxatini qaytaradi."""
    return WORD_PACKS


def get_pack(pack_id: str) -> dict | None:
    """ID bo'yicha paketni qaytaradi."""
    for p in WORD_PACKS:
        if p["id"] == pack_id:
            return p
    return None
