"""
Vocab Master Pro — Tayyor So'z Paketlari (Pre-made Word Packs).
O'quvchilar, talabalar va dasturchilar uchun saralangan maxsus lug'at to'plamlari.
Har bir so'z inglizcha, o'zbekcha tarjimasi va amaliy misol gapi (example) bilan ta'minlangan.
"""

WORD_PACKS = [
    {
        "id": "essential",
        "title": "🌟 Oltin 100 ta so'z (Essential Vocabulary)",
        "icon": "🌟",
        "level": "A2 - B1",
        "badge_color": "#F59E0B",
        "description": "Ingliz tilidagi eng ko'p ishlatiladigan, kundalik muloqot va asosiy tushunchalar uchun poydevor bo'luvchi 100 ta zaruriy so'z.",
        "words": [
            {"english": "achieve", "uzbek": "erishmoq, qo'lga kiritmoq", "example": "She worked hard to achieve her dream."},
            {"english": "advantage", "uzbek": "afzallik, ustunlik", "example": "Speed is the main advantage of this system."},
            {"english": "approach", "uzbek": "yondashuv, yaqinlashmoq", "example": "We need a new approach to solve this problem."},
            {"english": "attitude", "uzbek": "munosabat, qarash", "example": "A positive attitude helps you overcome difficulties."},
            {"english": "behavior", "uzbek": "xulq-atvor, yurish-turish", "example": "His behavior changed completely after the meeting."},
            {"english": "benefit", "uzbek": "foyda, naf", "example": "Regular exercise brings great benefits to health."},
            {"english": "challenge", "uzbek": "qiyinchilik, chaqiruv", "example": "Learning a new language is always an exciting challenge."},
            {"english": "community", "uzbek": "jamoa, jamiyat", "example": "The local community organized a charity event."},
            {"english": "compare", "uzbek": "taqqoslamoq, solishtirmoq", "example": "You should not compare your progress with others."},
            {"english": "conclude", "uzbek": "xulosa qilmoq, yakunlamoq", "example": "The report concludes that sales have increased."},
            {"english": "consider", "uzbek": "hisobga olmoq, o'ylab ko'rmoq", "example": "Please consider all options before making a decision."},
            {"english": "create", "uzbek": "yaratmoq, vujudga keltirmoq", "example": "Artists create beauty out of ordinary things."},
            {"english": "culture", "uzbek": "madaniyat", "example": "Travel helps you understand different cultures."},
            {"english": "decide", "uzbek": "qaror qilmoq", "example": "I need more time to decide what to do."},
            {"english": "describe", "uzbek": "tasvirlamoq, ta'riflamoq", "example": "Can you describe the person you saw?"},
            {"english": "develop", "uzbek": "rivojlantirmoq, taraqqiy etmoq", "example": "We need to develop our communication skills."},
            {"english": "difference", "uzbek": "farq, tafovut", "example": "Can you tell the difference between these two words?"},
            {"english": "discover", "uzbek": "kashf qilmoq, topmoq", "example": "Scientists continue to discover new species."},
            {"english": "economy", "uzbek": "iqtisodiyot", "example": "Tourism plays a big role in the national economy."},
            {"english": "effective", "uzbek": "samarali, ta'sirli", "example": "This is an effective strategy for learning words."},
            {"english": "environment", "uzbek": "atrof-muhit", "example": "We must protect our environment for future generations."},
            {"english": "essential", "uzbek": "muhim, zaruriy", "example": "Water is essential for all living creatures."},
            {"english": "evidence", "uzbek": "dalil, isbot", "example": "There is strong evidence supporting this theory."},
            {"english": "experience", "uzbek": "tajriba, kechinma", "example": "She gained valuable experience working abroad."},
            {"english": "explain", "uzbek": "tushuntirmoq, izohlamoq", "example": "The teacher explained the grammar rule clearly."},
            {"english": "explore", "uzbek": "o'rganmoq, tadqiq qilmoq", "example": "Let us explore new possibilities together."},
            {"english": "factor", "uzbek": "omil", "example": "Time is an important factor in this project."},
            {"english": "focus", "uzbek": "diqqatni qaratmoq", "example": "Try to focus on one task at a time."},
            {"english": "generate", "uzbek": "ishlab chiqarmoq, yaratmoq", "example": "Solar panels generate clean electricity."},
            {"english": "goal", "uzbek": "maqsad", "example": "Set a clear goal and work toward it every day."},
            {"english": "growth", "uzbek": "o'sish, rivojlanish", "example": "The company experienced rapid growth last year."},
            {"english": "identify", "uzbek": "aniqlamoq, tanimoq", "example": "The doctor was able to identify the disease quickly."},
            {"english": "impact", "uzbek": "ta'sir", "example": "Technology has a massive impact on modern education."},
            {"english": "improve", "uzbek": "yaxshilamoq, rivojlantirmoq", "example": "Daily practice will improve your English fluency."},
            {"english": "include", "uzbek": "o'z ichiga olmoq", "example": "The price includes breakfast and airport transfer."},
            {"english": "increase", "uzbek": "oshirmoq, ko'paytirmoq", "example": "We want to increase our daily study time."},
            {"english": "indicate", "uzbek": "ko'rsatmoq, dalolat bermoq", "example": "The symptoms indicate a common cold."},
            {"english": "influence", "uzbek": "ta'sir o'tkazmoq", "example": "Parents greatly influence their children's habits."},
            {"english": "information", "uzbek": "ma'lumot", "example": "You can find useful information on their website."},
            {"english": "insight", "uzbek": "teran tushunish, idrok", "example": "His book provides deep insights into human psychology."},
            {"english": "inspire", "uzbek": "ilhomlantirmoq", "example": "Great leaders inspire people to do their best."},
            {"english": "integrate", "uzbek": "birlashtirmoq, integratsiya qilmoq", "example": "The software is easy to integrate into existing workflows."},
            {"english": "introduce", "uzbek": "tanishtirmoq, joriy qilmoq", "example": "Let me introduce you to our new colleague."},
            {"english": "issue", "uzbek": "muammo, masala", "example": "We discussed environmental issues at the conference."},
            {"english": "knowledge", "uzbek": "bilim", "example": "Knowledge is power when put into practice."},
            {"english": "leadership", "uzbek": "yetakchilik, rahbarlik", "example": "Strong leadership helped the team succeed."},
            {"english": "maintain", "uzbek": "saqlab turmoq", "example": "It is important to maintain high quality standards."},
            {"english": "manage", "uzbek": "boshqarmoq, uddalamoq", "example": "She knows how to manage her time effectively."},
            {"english": "measure", "uzbek": "o'lchamoq, chora", "example": "We need to measure the results accurately."},
            {"english": "method", "uzbek": "usul, metod", "example": "This method has proven very successful."},
            {"english": "necessary", "uzbek": "zarur, kerakli", "example": "Patience is necessary when mastering a new skill."},
            {"english": "obtain", "uzbek": "qo'lga kiritmoq, olmoq", "example": "You must obtain a permit before entering."},
            {"english": "opportunity", "uzbek": "imkoniyat", "example": "Do not miss this great opportunity to study abroad."},
            {"english": "participate", "uzbek": "ishtirok etmoq", "example": "Many students participate in extracurricular activities."},
            {"english": "performance", "uzbek": "samaradorlik, ijro", "example": "His performance improved significantly this semester."},
            {"english": "perspective", "uzbek": "nuqtai nazar, dunyoqarash", "example": "Looking at things from another perspective is helpful."},
            {"english": "practice", "uzbek": "mashq qilmoq, amaliyot", "example": "Practice makes perfect."},
            {"english": "prepare", "uzbek": "tayyorlanmoq", "example": "We must prepare thoroughly for the upcoming exam."},
            {"english": "prevent", "uzbek": "oldini olmoq", "example": "Good habits prevent many health problems."},
            {"english": "primary", "uzbek": "asosiy, birlamchi", "example": "Education is our primary focus."},
            {"english": "priority", "uzbek": "ustuvor vazifa", "example": "Safety is always our top priority."},
            {"english": "problem", "uzbek": "muammo", "example": "Every problem has a solution if you think creatively."},
            {"english": "process", "uzbek": "jarayon", "example": "Learning a language is a gradual process."},
            {"english": "produce", "uzbek": "ishlab chiqarmoq", "example": "The factory produces high quality textiles."},
            {"english": "progress", "uzbek": "o'sish, ilgarilash", "example": "You are making steady progress in your English."},
            {"english": "promote", "uzbek": "rag'batlantirmoq, lavozimini oshirmoq", "example": "We want to promote healthy living among youth."},
            {"english": "protect", "uzbek": "himoya qilmoq", "example": "Wear a helmet to protect your head."},
            {"english": "provide", "uzbek": "ta'minlamoq, bermoq", "example": "The course provides all necessary learning materials."},
            {"english": "quality", "uzbek": "sifat", "example": "Focus on quality rather than quantity."},
            {"english": "realize", "uzbek": "anglab yetmoq", "example": "I did not realize how late it was."},
            {"english": "recognize", "uzbek": "tanimoq, e'tirof etmoq", "example": "I did not recognize him after so many years."},
            {"english": "reduce", "uzbek": "kamaytirmoq", "example": "We should reduce paper waste in the office."},
            {"english": "reflect", "uzbek": "aks ettirmoq, mulohaza qilmoq", "example": "Take time to reflect on what you learned today."},
            {"english": "relationship", "uzbek": "munosabat, aloqa", "example": "Trust is the foundation of any good relationship."},
            {"english": "relevant", "uzbek": "aloqador, ahamiyatli", "example": "Please provide all relevant documents."},
            {"english": "require", "uzbek": "talab qilmoq", "example": "This job requires excellent communication skills."},
            {"english": "research", "uzbek": "tadqiqot", "example": "Scientific research leads to innovation."},
            {"english": "resource", "uzbek": "resurs, manba", "example": "The library is an excellent resource for students."},
            {"english": "respond", "uzbek": "javob qaytarmoq", "example": "She quickly responded to my email."},
            {"english": "result", "uzbek": "natija", "example": "The test results will be announced tomorrow."},
            {"english": "reveal", "uzbek": "oshkor qilmoq", "example": "The survey revealed surprising facts about reading habits."},
            {"english": "significant", "uzbek": "muhim, sezilarli", "example": "There has been a significant increase in online learning."},
            {"english": "solution", "uzbek": "yechim", "example": "Finding a workable solution requires teamwork."},
            {"english": "source", "uzbek": "manba", "example": "Always cite your sources when writing an essay."},
            {"english": "specific", "uzbek": "aniq, muayyan", "example": "Can you give me a specific example?"},
            {"english": "strategy", "uzbek": "strategiya, reja", "example": "A well-planned strategy ensures victory."},
            {"english": "structure", "uzbek": "tuzilma, bino", "example": "The grammar structure is easy to understand."},
            {"english": "success", "uzbek": "muvaffaqiyat", "example": "Dedication is the secret to lasting success."},
            {"english": "support", "uzbek": "qo'llab-quvvatlamoq", "example": "Thank you for supporting me through hard times."},
            {"english": "technology", "uzbek": "texnologiya", "example": "Modern technology makes distance learning possible."},
            {"english": "tendency", "uzbek": "moyillik, tendensiya", "example": "There is a growing tendency toward remote work."},
            {"english": "theory", "uzbek": "nazariya", "example": "Einstein's theory changed modern physics forever."},
            {"english": "traditional", "uzbek": "an'anaviy", "example": "They wore beautiful traditional clothes at the festival."},
            {"english": "understand", "uzbek": "tushunmoq", "example": "I understand your point completely."},
            {"english": "unique", "uzbek": "noyob, betakror", "example": "Each person has a unique learning style."},
            {"english": "value", "uzbek": "qadr-qimmat, baholamoq", "example": "We value honesty and dedication in our team."},
            {"english": "variety", "uzbek": "turfa xillik, xilma-xillik", "example": "The market offers a wide variety of fresh fruits."},
            {"english": "various", "uzbek": "turli xil, har xil", "example": "There are various ways to memorize new vocabulary."},
            {"english": "visible", "uzbek": "ko'rinadigan, aniq", "example": "The mountain was visible from miles away."},
        ]
    },
    {
        "id": "ielts",
        "title": "🎓 IELTS Band 7+ Academic Vocabulary",
        "icon": "🎓",
        "level": "B2 - C1",
        "badge_color": "#8B5CF6",
        "description": "IELTS Writing va Reading imtihonlarida yuqori ball (Band 7+) olish uchun eng qimmatli akademik so'zlar to'plami.",
        "words": [
            {"english": "acquire", "uzbek": "o'zlashtirmoq, orttirmoq", "example": "Children acquire language naturally through immersion."},
            {"english": "advocate", "uzbek": "tarafdor bo'lmoq, yoqlamoq", "example": "Many experts advocate for renewable energy sources."},
            {"english": "allocate", "uzbek": "taqsimlamoq, ajratmoq", "example": "The government allocated extra funds for healthcare."},
            {"english": "ambiguous", "uzbek": "noaniq, ikki ma'noli", "example": "The instructions were ambiguous, causing confusion."},
            {"english": "anticipate", "uzbek": "oldindan sezmoq, kutmoq", "example": "We anticipate a sharp rise in demand this winter."},
            {"english": "coherent", "uzbek": "mantiqiy, bog'langan", "example": "Your essay should have a clear and coherent structure."},
            {"english": "commence", "uzbek": "boshlanmoq, boshlamoq", "example": "The lecture will commence promptly at nine o'clock."},
            {"english": "compensate", "uzbek": "qoplamoq, kompensatsiya qilmoq", "example": "The company compensated workers for the extra hours."},
            {"english": "comprehensive", "uzbek": "har tomonlama, to'liq", "example": "The report offers a comprehensive review of the economy."},
            {"english": "consensus", "uzbek": "yakdillik, umumiy kelishuv", "example": "The committee reached a consensus on the proposal."},
            {"english": "constitute", "uzbek": "tashkil qilmoq, hisoblanmoq", "example": "Women constitute over half of university graduates."},
            {"english": "constrain", "uzbek": "cheklamoq, majburlamoq", "example": "Budget limits constrain our ability to expand."},
            {"english": "contradict", "uzbek": "zid kelmoq, inkor qilmoq", "example": "The new findings contradict previous assumptions."},
            {"english": "deduce", "uzbek": "mantiqan xulosa chiqarmoq", "example": "From the clues, the detective deduced what had happened."},
            {"english": "depict", "uzbek": "tasvirlamoq", "example": "The documentary depicts life in rural communities."},
            {"english": "diminish", "uzbek": "kamaymoq, zaiflashmoq", "example": "The pain will gradually diminish after taking medicine."},
            {"english": "discreet", "uzbek": "ehtiyotkor, bosiq", "example": "He made discreet inquiries about the job opening."},
            {"english": "empirical", "uzbek": "tajribaga asoslangan", "example": "Her conclusions are backed by solid empirical data."},
            {"english": "enhance", "uzbek": "kuchaytirmoq, sifatini oshirmoq", "example": "Interactive tools enhance student engagement."},
            {"english": "explicit", "uzbek": "ochiq-oydin, aniq", "example": "The teacher gave explicit directions for the project."},
            {"english": "fluctuate", "uzbek": "o'zgarib turmoq, tebranmoq", "example": "Prices fluctuate depending on supply and demand."},
            {"english": "hierarchy", "uzbek": "iyerarxiya, pog'ona", "example": "There is a strict hierarchy in military organizations."},
            {"english": "hypothesis", "uzbek": "gipoteza, ilmiy faraz", "example": "Scientists conducted experiments to test the hypothesis."},
            {"english": "inevitable", "uzbek": "muqarrar, qochib bo'lmas", "example": "Change is an inevitable part of modern life."},
            {"english": "inherent", "uzbek": "tug'ma, ajralmas", "example": "Every sport has an inherent risk of minor injuries."},
            {"english": "mitigate", "uzbek": "yumshatmoq, xavfni kamaytirmoq", "example": "Planting trees helps mitigate the effects of pollution."},
            {"english": "notion", "uzbek": "tushuncha, fikr", "example": "He dismissed the notion that success is purely luck."},
            {"english": "perceive", "uzbek": "idrok etmoq, his qilmoq", "example": "People perceive color differently in various lights."},
            {"english": "plausible", "uzbek": "haqiqatga yaqin, ishonarli", "example": "She offered a plausible explanation for her absence."},
            {"english": "prevalent", "uzbek": "keng tarqalgan", "example": "Stress is prevalent among high school seniors."},
            {"english": "qualitative", "uzbek": "sifatga oid", "example": "The researchers conducted qualitative interviews."},
            {"english": "quantitative", "uzbek": "miqdoriy", "example": "Quantitative analysis showed a 20 percent increase."},
            {"english": "scrutinize", "uzbek": "sinchiklab tekshirmoq", "example": "Auditors will scrutinize every financial transaction."},
            {"english": "subsequent", "uzbek": "keyingi, undan keyin keladigan", "example": "Subsequent studies confirmed the original findings."},
            {"english": "substantial", "uzbek": "sezilarli, salmoqli", "example": "A substantial amount of money was saved."},
            {"english": "subtle", "uzbek": "nozik, sezilmas", "example": "There was a subtle change in his tone of voice."},
            {"english": "trigger", "uzbek": "sabab bo'lmoq, qo'zg'atmoq", "example": "Cold weather can trigger asthma attacks."},
            {"english": "unprecedented", "uzbek": "misli ko'rilmagan", "example": "The crisis caused unprecedented economic disruption."},
            {"english": "viable", "uzbek": "yashovchan, hayotiy", "example": "Solar energy is now a commercially viable option."},
            {"english": "advocate", "uzbek": "himoyachi, yoqlovchi", "example": "She is a passionate advocate of human rights."}
        ]
    },
    {
        "id": "tech",
        "title": "💻 IT & Dasturlash (Tech & Coding)",
        "icon": "💻",
        "level": "Professional Tech",
        "badge_color": "#10B981",
        "description": "Dasturchilar, testerlar va IT mutaxassislari uchun kod yozish, dokumentatsiya va suhbatlarda kerak bo'ladigan texnik terminlar.",
        "words": [
            {"english": "algorithm", "uzbek": "algoritm, amallar ketma-ketligi", "example": "We optimized the search algorithm to reduce complexity."},
            {"english": "architecture", "uzbek": "dasturiy arxitektura", "example": "Microservice architecture allows independent scaling."},
            {"english": "authentication", "uzbek": "autentifikatsiya, shaxsni tasdiqlash", "example": "Two-factor authentication adds extra security."},
            {"english": "authorization", "uzbek": "avtorizatsiya, ruxsat berish", "example": "Authorization ensures users access only their own data."},
            {"english": "backend", "uzbek": "server qismi", "example": "The backend handles business logic and database queries."},
            {"english": "benchmark", "uzbek": "samaradorlik testi", "example": "Running benchmarks showed a 40% memory saving."},
            {"english": "breakpoint", "uzbek": "to'xtash nuqtasi (debugging)", "example": "Set a breakpoint inside the function to inspect variables."},
            {"english": "buffer", "uzbek": "vaqtinchalik xotira maydoni", "example": "Audio streaming uses a buffer to prevent stuttering."},
            {"english": "cache", "uzbek": "kesh, tezkor xotira", "example": "Redis is commonly used as an in-memory cache."},
            {"english": "callback", "uzbek": "qayta chaqiriluvchi funksiya", "example": "Pass a callback function to handle the async response."},
            {"english": "compiler", "uzbek": "kompilyator", "example": "The compiler translates source code into machine bytecode."},
            {"english": "concurrency", "uzbek": "bir vaqtda bajarilish, parallellik", "example": "Go routines make handling concurrency straightforward."},
            {"english": "deadlock", "uzbek": "tupik, o'zaro kutib qolish", "example": "Improper mutex locks can cause a program deadlock."},
            {"english": "debugging", "uzbek": "xatoliklarni topish va tuzatish", "example": "Debugging often takes more time than writing new code."},
            {"english": "dependency", "uzbek": "bog'liqlik (kutubxona)", "example": "Pip installs third-party dependencies from requirements.txt."},
            {"english": "deployment", "uzbek": "joylashtirish, ishga tushirish (deploy)", "example": "Automated deployment saves developers hours of manual work."},
            {"english": "encapsulation", "uzbek": "inkapsulyatsiya (OOP)", "example": "Encapsulation hides the internal state of an object."},
            {"english": "endpoint", "uzbek": "API oxirgi manzili", "example": "The REST endpoint returns user profile data in JSON."},
            {"english": "exception", "uzbek": "istisno holati, kutilmagan xato", "example": "Catch the exception to prevent the application from crashing."},
            {"english": "execute", "uzbek": "ishga tushirmoq, bajarmoq", "example": "The CPU executes millions of instructions per second."},
            {"english": "framework", "uzbek": "freymvork, dasturiy qolip", "example": "Django is a popular Python web framework."},
            {"english": "frontend", "uzbek": "foydalanuvchi interfeysi qismi", "example": "Modern frontends are built using React or Vue."},
            {"english": "immutable", "uzbek": "o'zgarmas (ma'lumot)", "example": "Tuples and strings in Python are immutable."},
            {"english": "inheritance", "uzbek": "meros olish (OOP)", "example": "Class inheritance promotes code reuse across models."},
            {"english": "instance", "uzbek": "nusxa, obyekt nusxasi", "example": "Create a new instance of the DatabaseConnection class."},
            {"english": "iteration", "uzbek": "takrorlanish, qadam", "example": "The loop executes ten iterations before terminating."},
            {"english": "latency", "uzbek": "kechikish vaqti (ping)", "example": "Low latency is critical for online multiplayer gaming."},
            {"english": "middleware", "uzbek": "oraliq dasturiy ta'minot", "example": "Authentication middleware checks tokens before each request."},
            {"english": "migration", "uzbek": "ma'lumotlar bazasi migratsiyasi", "example": "Run the migration script to add the new table column."},
            {"english": "multithreading", "uzbek": "ko'p oqimli ishlash", "example": "Multithreading improves responsiveness in GUI desktop apps."},
            {"english": "namespace", "uzbek": "nomlar fazosi", "example": "Namespaces prevent naming collisions in large projects."},
            {"english": "optimization", "uzbek": "optimallashtirish", "example": "Code optimization reduced loading time from 5s to 1s."},
            {"english": "overflow", "uzbek": "to'lib toshish (xotira)", "example": "Deep recursion without a base case causes stack overflow."},
            {"english": "pagination", "uzbek": "sahifalarga bo'lish", "example": "API pagination returns results 20 items per page."},
            {"english": "parameter", "uzbek": "parametr, argument", "example": "Pass the user ID as a parameter to the function."},
            {"english": "payload", "uzbek": "foydali yuk, so'rov tanasi", "example": "The POST request carries a JSON payload with form data."},
            {"english": "pipeline", "uzbek": "konveyer (CI/CD)", "example": "The CI/CD pipeline runs unit tests on every git push."},
            {"english": "polymorphism", "uzbek": "polimorfizm (OOP)", "example": "Polymorphism allows different classes to share an interface."},
            {"english": "protocol", "uzbek": "tarmoq protokoli", "example": "HTTPS is the standard secure communication protocol."},
            {"english": "query", "uzbek": "ma'lumotlar bazasi so'rovi", "example": "Write an indexed SQL query for faster data retrieval."},
            {"english": "recursion", "uzbek": "rekursiya, o'zini chaqirish", "example": "A recursive function must have a terminating base condition."},
            {"english": "refactoring", "uzbek": "kodni qayta ishlash, tozalash", "example": "Refactoring improves readability without altering functionality."},
            {"english": "repository", "uzbek": "ombor, kod repozitoriysi", "example": "Clone the git repository to your local computer."},
            {"english": "responsive", "uzbek": "moslashuvchan (dizayn)", "example": "Responsive web design adapts seamlessly to mobile screens."},
            {"english": "runtime", "uzbek": "ishlash vaqti muhiti", "example": "Python runtime executes bytecode inside a virtual machine."},
            {"english": "sandbox", "uzbek": "qumloq, izolyatsiyalangan muhit", "example": "Run untrusted scripts inside a sandbox for safety."},
            {"english": "scalability", "uzbek": "kengayuvchanlik", "example": "Cloud computing provides high scalability during traffic spikes."},
            {"english": "serialization", "uzbek": "obyektni matnga aylantirish", "example": "JSON serialization transforms objects into string format."},
            {"english": "syntax", "uzbek": "sintaksis, til qoidalari", "example": "A missing closing bracket causes a syntax error."},
            {"english": "throughput", "uzbek": "o'tkazuvchanlik quvvati", "example": "We benchmarked the server throughput under 10,000 requests."},
            {"english": "transaction", "uzbek": "tranzaksiya (DB)", "example": "Wrap database operations in a transaction for atomicity."},
            {"english": "validation", "uzbek": "tekshirish, tasdiqlash", "example": "Input validation prevents SQL injection attacks."}
        ]
    },
    {
        "id": "idioms",
        "title": "🗣 Kundalik Iboralar & Frazeologizmlar (Collocations)",
        "icon": "🗣",
        "level": "Spoken English",
        "badge_color": "#EC4899",
        "description": "Chet elliklar kabi tabiiy va jonli gapirish uchun eng mashhur 35 ta inglizcha ibora va turg'un birikmalar.",
        "words": [
            {"english": "call it a day", "uzbek": "ishni tugatmoq, bugunga yetar demoq", "example": "We have been working for ten hours, let's call it a day."},
            {"english": "piece of cake", "uzbek": "juda oson ish, bir cho'qishda", "example": "Don't worry about the driving test, it is a piece of cake."},
            {"english": "break the ice", "uzbek": "muzni eritmoq, suhbatni boshlab berish", "example": "He told a funny joke to break the ice at the party."},
            {"english": "bite the bullet", "uzbek": "tishni tishga qo'ymoq, og'ir ishga botinmoq", "example": "I hate dentist visits, but I just have to bite the bullet."},
            {"english": "under the weather", "uzbek": "o'zini noxush/betob his qilmoq", "example": "I cannot come to work today because I feel under the weather."},
            {"english": "once in a blue moon", "uzbek": "juda kamdan-kam, yilda bir marta", "example": "He lives far away, so we only see him once in a blue moon."},
            {"english": "see eye to eye", "uzbek": "fikrlari bir joydan chiqmoq, hamfikr bo'lmoq", "example": "My brother and I rarely see eye to eye on politics."},
            {"english": "costs an arm and a leg", "uzbek": "juda qimmat turadi, o't tushgan", "example": "That luxury sports car costs an arm and a leg."},
            {"english": "burn the midnight oil", "uzbek": "tun bo'yi bedor ishlamoq/o'qimoq", "example": "She burned the midnight oil to prepare for the bar exam."},
            {"english": "cut corners", "uzbek": "ishni osonlatib sifatdan urmoq, chala qilmoq", "example": "Never cut corners when building electrical wiring."},
            {"english": "back to the drawing board", "uzbek": "boshidan boshlamoq (reja o'xshamaganda)", "example": "The prototype failed, so it is back to the drawing board."},
            {"english": "beat around the bush", "uzbek": "gapni aylantirmoq, asosiy mavzudan qochmoq", "example": "Stop beating around the bush and tell me the truth."},
            {"english": "by the way", "uzbek": "darvoqe, aytgandek", "example": "By the way, did you remember to buy the milk?"},
            {"english": "as soon as possible", "uzbek": "iloji boricha tezroq", "example": "Please send the completed report as soon as possible."},
            {"english": "keep in touch", "uzbek": "aloqada bo'lib turmoq", "example": "It was great seeing you; let's keep in touch!"},
            {"english": "make up your mind", "uzbek": "bir qarorga kelmoq", "example": "You need to make up your mind before the deadline."},
            {"english": "on the other hand", "uzbek": "boshqa tomondan qaraganda", "example": "The job pays well; on the other hand, it requires long hours."},
            {"english": "in the long run", "uzbek": "uzoq muddatda, pirovardida", "example": "Investing in your education always pays off in the long run."},
            {"english": "sooner or later", "uzbek": "erta yo kech, baribir", "example": "Sooner or later, hard work brings rewarding results."},
            {"english": "from scratch", "uzbek": "noldan, boshidan", "example": "He built his tech startup completely from scratch."},
            {"english": "out of the blue", "uzbek": "to'satdan, kutilmaganda", "example": "She received a job offer out of the blue from Google."},
            {"english": "point of view", "uzbek": "nuqtai nazar", "example": "Try to look at the situation from a customer's point of view."},
            {"english": "give it a shot", "uzbek": "urinib/sinab ko'rmoq", "example": "Even if it looks hard, you should definitely give it a shot."},
            {"english": "hit the books", "uzbek": "dars qilmoq, kitob o'qishga kirishmoq", "example": "Exams start next Monday, so it's time to hit the books."},
            {"english": "keep an eye on", "uzbek": "ko'z-quloq bo'lmoq", "example": "Could you please keep an eye on my luggage for a minute?"},
            {"english": "let someone down", "uzbek": "umidini puchga chiqarmoq, pand bermoq", "example": "I promised to help, and I will not let you down."},
            {"english": "make ends meet", "uzbek": "ro'zg'orni zo'rg'a tebratmoq", "example": "Many families worked two jobs to make ends meet."},
            {"english": "on the same page", "uzbek": "bir xil tushunmoq, hamfikr bo'lmoq", "example": "Let us have a quick sync to make sure we are on the same page."},
            {"english": "ring a bell", "uzbek": "tanish tuyulmoq, eshitgandek bo'lmoq", "example": "His name rings a bell, but I cannot recall his face."},
            {"english": "take it easy", "uzbek": "o'zingni bosing, xotirjam bo'ling", "example": "Take it easy; the weekend is finally here."},
            {"english": "time flies", "uzbek": "vaqt qushdek uchadi", "example": "Time flies when you are having fun with friends."},
            {"english": "up in the air", "uzbek": "hali noaniq, havoda muallaq", "example": "Our vacation plans are still up in the air due to work."},
            {"english": "spill the beans", "uzbek": "sirni ochib qo'ymoq", "example": "Don't spill the beans about the surprise birthday party."},
            {"english": "step up your game", "uzbek": "o'yinni/harakatni kuchaytirmoq", "example": "Competition is fierce, so you must step up your game."},
            {"english": "hit the nail on the head", "uzbek": "gapning nishoniga urmoq, to'g'ri topmoq", "example": "Your analysis hit the nail on the head perfectly."}
        ]
    },
    {
        "id": "business",
        "title": "💼 Biznes, Moliya & Karyera (Business English)",
        "icon": "💼",
        "level": "B2 - C1",
        "badge_color": "#10B981",
        "description": "Muzokaralar, investitsiyalar, bank ishi, shartnomalar va professional faoliyat uchun 30 ta eng sara biznes atamalar.",
        "words": [
            {"english": "revenue", "uzbek": "daromad, tushum", "example": "The company reported a 20% increase in annual revenue."},
            {"english": "negotiate", "uzbek": "muzokara olib bormoq", "example": "We need to negotiate better terms with the suppliers."},
            {"english": "investment", "uzbek": "investitsiya, sarmoya", "example": "Real estate is considered a safe long-term investment."},
            {"english": "profitability", "uzbek": "foydalilik, rentabellik", "example": "Our primary goal this quarter is to improve profitability."},
            {"english": "stakeholder", "uzbek": "manfaatdor tomon", "example": "All key stakeholders approved the project budget."},
            {"english": "contract", "uzbek": "shartnoma, bitim", "example": "Both parties signed the contract yesterday."},
            {"english": "merger", "uzbek": "birlashish (kompaniyalar)", "example": "The merger created the largest telecom company in the region."},
            {"english": "liability", "uzbek": "majburiyat, javobgarlik", "example": "The business must pay off its short-term liabilities."},
            {"english": "dividend", "uzbek": "dividend, aksiyador ulushi", "example": "Shareholders received a higher dividend this year."},
            {"english": "benchmark", "uzbek": "mezon, etalon ko'rsatkich", "example": "This product sets a new benchmark for industry quality."},
            {"english": "portfolio", "uzbek": "investitsiya portfeli", "example": "Diversifying your portfolio reduces financial risk."},
            {"english": "inflation", "uzbek": "inflyatsiya, narx oshishi", "example": "Central banks raise interest rates to combat inflation."},
            {"english": "franchise", "uzbek": "franshiza, savdo huquqi", "example": "He opened a fast-food franchise in the city center."},
            {"english": "entrepreneur", "uzbek": "tadbirkor, ishbilarmon", "example": "Successful entrepreneurs are willing to take calculated risks."},
            {"english": "leverage", "uzbek": "moliyaviy dastak, foydalanmoq", "example": "We can leverage our market position to attract top talent."},
            {"english": "acquisition", "uzbek": "sotib olish (kompaniyani)", "example": "The company announced the acquisition of an AI startup."},
            {"english": "deficit", "uzbek": "kamomad, defitsit", "example": "The government is trying to reduce the trade deficit."},
            {"english": "compliance", "uzbek": "muvofiqlik, qoidalarga rioya", "example": "Ensure full compliance with financial regulations."},
            {"english": "turnover", "uzbek": "aylanma mablag', kadrlar almashinishi", "example": "High staff turnover negatively impacts team productivity."},
            {"english": "monopoly", "uzbek": "monopoliya, yakka hukmronlik", "example": "Antitrust laws prevent tech giants from forming a monopoly."},
            {"english": "equity", "uzbek": "o'z sarmoyasi, aksiya kapitali", "example": "He owns a 15% equity stake in the company."},
            {"english": "outsourcing", "uzbek": "tashqi xizmatdan foydalanish", "example": "Outsourcing customer support helped reduce operational costs."},
            {"english": "subsidiary", "uzbek": "shu'ba korxona", "example": "The conglomerate owns multiple subsidiaries worldwide."},
            {"english": "procurement", "uzbek": "xarid qilish, ta'minot", "example": "The procurement department handles all vendor contracts."},
            {"english": "restructuring", "uzbek": "qayta tashkil etish", "example": "Debt restructuring saved the company from bankruptcy."},
            {"english": "feasibility", "uzbek": "amalga osha olishlik, texnik-iqtisodiy asos", "example": "We conducted a feasibility study before launching the project."},
            {"english": "synergy", "uzbek": "sinergiya, birgalikdagi kuch", "example": "The two teams created great synergy working together."},
            {"english": "depreciation", "uzbek": "eskirish, amortizatsiya", "example": "Vehicle depreciation must be factored into annual costs."},
            {"english": "collateral", "uzbek": "garov (kredit uchun)", "example": "He used his property as collateral for the bank loan."},
            {"english": "contingency", "uzbek": "kutilmagan holat rejasi", "example": "Always have a contingency fund for emergency expenses."}
        ]
    },
    {
        "id": "travel",
        "title": "✈️ Sayohat & Aeroport (Travel & Survival)",
        "icon": "✈️",
        "level": "A1 - B1",
        "badge_color": "#3B82F6",
        "description": "Xorijiy safarlar, aeroport, mehmonxona, bojxona va shahar bo'ylab sayohat qilish uchun 30 ta amaliy so'z.",
        "words": [
            {"english": "boarding pass", "uzbek": "samolyotga chiqish taloni", "example": "Please have your passport and boarding pass ready."},
            {"english": "customs", "uzbek": "bojxona", "example": "You must declare expensive goods at customs."},
            {"english": "departure", "uzbek": "jo'nab ketish, uchish", "example": "The departure board shows flights to London and Paris."},
            {"english": "arrival", "uzbek": "yetib kelish, kutib olish", "example": "Our estimated time of arrival is 6:00 PM."},
            {"english": "luggage", "uzbek": "bagaj, yuk", "example": "Passengers are allowed one piece of hand luggage."},
            {"english": "reservation", "uzbek": "band qilish, bron", "example": "I made a hotel reservation for three nights."},
            {"english": "itinerary", "uzbek": "sayohat rejasi, marshrut", "example": "Here is our detailed travel itinerary for Italy."},
            {"english": "accommodation", "uzbek": "turar joy, yashash joyi", "example": "The conference organizers provide free accommodation."},
            {"english": "currency exchange", "uzbek": "valyuta ayirboshlash", "example": "Find a currency exchange booth with favorable rates."},
            {"english": "passport control", "uzbek": "pasport nazorati", "example": "Wait in line at passport control with your documents."},
            {"english": "delay", "uzbek": "kechikish", "example": "The flight was delayed due to heavy fog."},
            {"english": "gate", "uzbek": "samolyotga chiqish eshigi", "example": "Boarding will begin at gate number 14."},
            {"english": "terminal", "uzbek": "aeroport terminali", "example": "International flights depart from Terminal 2."},
            {"english": "shuttle", "uzbek": "muntazam qatnovchi avtobus", "example": "Take the free airport shuttle to the car rental center."},
            {"english": "sightseeing", "uzbek": "diqqatga sazovor joylarni tomosha qilish", "example": "We spent the whole afternoon sightseeing in Istanbul."},
            {"english": "destination", "uzbek": "manzil, boriladigan joy", "example": "Paris is one of the world's top tourist destinations."},
            {"english": "ticket counter", "uzbek": "chipta sotish kassasi", "example": "You can buy train tickets at the ticket counter."},
            {"english": "flight attendant", "uzbek": "styuard / styuardessa", "example": "The flight attendant demonstrated the safety procedures."},
            {"english": "baggage claim", "uzbek": "yukni qabul qilib olish joyi", "example": "Collect your checked bags at the baggage claim carousel."},
            {"english": "carry-on", "uzbek": "qo'l yuki", "example": "Keep your laptop and medicines in your carry-on bag."},
            {"english": "connection flight", "uzbek": "oraliq ulanish reysi (perevod)", "example": "We have a two-hour connection flight in Dubai."},
            {"english": "emergency exit", "uzbek": "favqulodda chiqish eshigi", "example": "Do not block the emergency exit row with bags."},
            {"english": "fare", "uzbek": "yo'l haqi, chipta narxi", "example": "The taxi fare from the airport to the city was $30."},
            {"english": "guided tour", "uzbek": "gid hamrohligidagi sayohat", "example": "We booked a guided tour of the historical museum."},
            {"english": "hostel", "uzbek": "arzon mehmonxona (yotoqxona)", "example": "Backpackers often stay in hostels to save money."},
            {"english": "landmark", "uzbek": "mashhur me'moriy yodgorlik", "example": "The Eiffel Tower is the most famous landmark in France."},
            {"english": "lost and found", "uzbek": "topilmalar byurosi", "example": "Check the lost and found office if you misplaced your bag."},
            {"english": "subway", "uzbek": "metro", "example": "Taking the subway is the fastest way to travel across New York."},
            {"english": "validity", "uzbek": "amal qilish muddati", "example": "Check the validity of your passport before booking tickets."},
            {"english": "visa", "uzbek": "viza, kirish ruxsatnomasi", "example": "Apply for your travel visa at least one month in advance."}
        ]
    },
    {
        "id": "phrasal_verbs",
        "title": "🚀 40 ta Muhim Iborali Fe'l (Phrasal Verbs Master)",
        "icon": "🚀",
        "level": "B1 - B2",
        "badge_color": "#8B5CF6",
        "description": "Ingliz tilida eng ko'p adashtiradigan va imtihonlarda (IELTS, CEFR) eng ko'p tushadigan turg'un iborali fe'llar.",
        "words": [
            {"english": "give up", "uzbek": "taslim bo'lmoq, voz kechmoq", "example": "Never give up on your dreams, no matter how hard it gets."},
            {"english": "look forward to", "uzbek": "intizorlik bilan kutmoq", "example": "I really look forward to meeting you next week."},
            {"english": "figure out", "uzbek": "tushunib yetmoq, yechimini topmoq", "example": "Can you help me figure out how this machine works?"},
            {"english": "carry on", "uzbek": "davom ettirmoq", "example": "Please carry on with your work while I take this call."},
            {"english": "turn down", "uzbek": "rad etmoq (taklifni)", "example": "She turned down the job offer because the salary was too low."},
            {"english": "bring up", "uzbek": "tarbiyalamoq, mavzuni ko'tarmoq", "example": "He brought up an interesting question during the meeting."},
            {"english": "put off", "uzbek": "keyinga qoldirmoq", "example": "Never put off until tomorrow what you can do today."},
            {"english": "call off", "uzbek": "bekor qilmoq", "example": "The match was called off because of heavy rain."},
            {"english": "run into", "uzbek": "tasodifan uchratmoq", "example": "I ran into an old classmate at the supermarket."},
            {"english": "find out", "uzbek": "aniqlamoq, bilib olmoq", "example": "We need to find out what caused the system outage."},
            {"english": "get along with", "uzbek": "yaxshi chiqishmoq, til topishmoq", "example": "She gets along well with all her new colleagues."},
            {"english": "come up with", "uzbek": "yangi g'oya / fikr o'ylab topmoq", "example": "He came up with a brilliant marketing strategy."},
            {"english": "set up", "uzbek": "asos solmoq, o'rnatmoq", "example": "They set up a new software company in Silicon Valley."},
            {"english": "break down", "uzbek": "buzilib qolmoq (mashina, texnika)", "example": "Our car broke down on the highway yesterday."},
            {"english": "catch up with", "uzbek": "yetib olmoq (tenglashmoq)", "example": "Study hard to catch up with the rest of the class."},
            {"english": "take off", "uzbek": "uchib ketmoq (samolyot), yechmoq (kiyim)", "example": "The plane took off smoothly despite windy weather."},
            {"english": "drop off", "uzbek": "tashlab qo'ymoq (mashinada)", "example": "I can drop you off at the train station on my way to work."},
            {"english": "hold on", "uzbek": "kutib turmoq (telefonda)", "example": "Hold on a second, let me grab a pen."},
            {"english": "give in", "uzbek": "taslim bo'lmoq, ko'nmoq", "example": "After hours of debate, he finally gave in to our proposal."},
            {"english": "look into", "uzbek": "o'rganib chiqmoq, tekshirmoq", "example": "The manager promised to look into the customer complaint."},
            {"english": "make up", "uzbek": "to'qib chiqarmoq, yarashmoq", "example": "He made up an excuse for being late to class."},
            {"english": "point out", "uzbek": "ko'rsatib bermoq, e'tibor qaratmoq", "example": "Thank you for pointing out that grammar mistake."},
            {"english": "show up", "uzbek": "paydo bo'lmoq, kelmoq", "example": "He promised to come but did not show up."},
            {"english": "work out", "uzbek": "mashq qilmoq, o'xshamoq/yaxshi yakunlanmoq", "example": "Don't worry, everything will work out in the end."},
            {"english": "cut down on", "uzbek": "kamaytirmoq (iste'molni)", "example": "You should cut down on sugar for better health."},
            {"english": "keep up with", "uzbek": "orqada qolmaslik, hamqadam bo'lmoq", "example": "It is hard to keep up with the rapid pace of AI development."},
            {"english": "turn up", "uzbek": "ovozini ko'tarmoq, to'satdan topilmoq", "example": "My lost keys turned up inside my winter jacket pocket."},
            {"english": "take after", "uzbek": "o'xshamoq (ota-onasiga)", "example": "He takes after his father in both looks and temperament."},
            {"english": "pass away", "uzbek": "vafot etmoq", "example": "His grandfather passed away peacefully at the age of ninety."},
            {"english": "back up", "uzbek": "nusxa olmoq (fayl), qo'llab-quvvatlamoq", "example": "Always back up your files before running software updates."},
            {"english": "fall apart", "uzbek": "bo'laklarga bo'linib ketmoq, yemirilmoq", "example": "The old book started to fall apart from frequent use."},
            {"english": "go through", "uzbek": "boshidan kechirmoq (qiyinchilikni)", "example": "She went through a lot of hardships before succeeding."},
            {"english": "let down", "uzbek": "pand bermoq, umidni puchga chiqarmoq", "example": "Trust me, I will not let you down this time."},
            {"english": "look up to", "uzbek": "hurmat qilmoq, havas qilmoq", "example": "Young athletes always look up to Olympic champions."},
            {"english": "pay off", "uzbek": "o'zini oqlamoq, mevasini bermoq", "example": "All your sleepless nights of studying will pay off."},
            {"english": "stand out", "uzbek": "ajralib turmoq", "example": "Her creative design truly stood out from the competition."},
            {"english": "watch out", "uzbek": "ehtiyot bo'lmoq", "example": "Watch out! The floor is slippery."},
            {"english": "cheer up", "uzbek": "kayfiyatni ko'tarmoq", "example": "Cheer up, tomorrow is a brand new day!"},
            {"english": "hang out", "uzbek": "vaqtni birga o'tkazmoq (do'stlar bilan)", "example": "We love hanging out at the local coffee shop on Sundays."},
            {"english": "grow up", "uzbek": "ulg'aymoq, katta bo'lmoq", "example": "He grew up in a small town near the mountains."}
        ]
    }
]


def get_all_packs() -> list[dict]:
    """Barcha mavjud paketlar ro'yxatini qaytaradi."""
    return WORD_PACKS


def get_pack(pack_id: str) -> dict | None:
    """ID bo'yicha paketni qaytaradi."""
    for p in WORD_PACKS:
        if p["id"] == pack_id:
            return p
    return None
